server:
  port: 8003


spring:
  application:
    name: demo
  datasource:
    name: demo
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://124.221.161.153:3302/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 10240MB  #\u5355\u4E2A\u6587\u4EF6\u5927\u5C0F\u9650\u5236
      max-request-size: 10240MB #\u603B\u6587\u4EF6\u5927\u5C0F\u9650\u5236\uFF08\u5141\u8BB8\u5B58\u50A8\u6587\u4EF6\u7684\u6587\u4EF6\u5939\u5927\u5C0F\uFF09
  redis:
    host: localhost
    port: 6379
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#\u914D\u7F6E\u7C7B\u578B\u522B\u540D\u6240\u5BF9\u5E94\u7684\u5305
  type-aliases-package: com.example.demo.mybatisplus.pojo