server:
  port: 8003


spring:
  application:
    name: test
  datasource:
    name: easy-excel-study
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
#  servlet:
#    multipart:
#      max-file-size: 10240MB  #单个文件大小限制
#      max-request-size: 10240MB #总文件大小限制（允许存储文件的文件夹大小）
#
#file:
#  path: F:/movie/