server:
  port: 8003


spring:
  application:
    name: test
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.131.52:1521:dev12c
    username: MSA_DG_DECL
    password: easipass
  #    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
#    username: root
#    password: root
  servlet:
    multipart:
      max-file-size: 10240MB  #单个文件大小限制
      max-request-size: 10240MB #总文件大小限制（允许存储文件的文件夹大小）
  jpa:
    database: oracle
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  redis:
    host: 124.221.161.153
    password: root